### ISSUE TITLE
The newest update (For october 2021) seems to have broke the mod 

### ISSUE THREAD

**Issue by the-deserter** [tparker48/Disco-Explorer-Remastered#1]
The newest update reduced the game size from around 20 gigs to around 9 gigs, that might be the reason for it.

**Comment by tparker48** [comment]
Fixed! 

The [Unity Explorer](https://github.com/sinai-dev/UnityExplorer/tree/master/src) tool is fantastic, and allowed me to finally diagnose and solve the issue after a lot of head scratching.
